### ISSUE TITLE
MutabilityAnalysisException thrown during analysis

### ISSUE THREAD

**Issue by nickantzoulis** [MutabilityDetector/MutabilityDetector#115] opened 2018-06-11 15:37 UTC
ERROR:

[INFO] --- findbugs-maven-plugin:3.0.5:findbugs (findbugs) @ fb-tests ---
[INFO] Fork Value is true
     [java] Registered plugin detector [MutabilityDetector4FindBugs]
     [java] The following errors occurred during analysis:
     [java]   Exception analyzing nick.HistoryItem using detector org.mutabilitydetector.findbugs.MutabilityDetector4FindBugs
     [java]     org.mutabilitydetector.checkers.MutabilityAnalysisException: 
     [java] An unhandled error occurred. Please read message at end of this output.
     [java] Class being analysed: nick.HistoryItem
     [java] Checker that failed: CanSubclassChecker
     [java] Classes analysed so far:
     [java] An unhandled error occurred. This is probably my fault, not yours, and I am sorry.
     [java] I'd love to get an opportunity to fix this, please report as an issue at:
     [java]  https://github.com/MutabilityDetector/MutabilityDetector/issues/ 
     [java] Pasting in this error message and stack trace, and if possible, 
     [java] information about the code causing the error. 
     [java] For example, one of: 
     [java]     .class files (preferably with source);
     [java]     compilable .java files; 
     [java]     a jar (again preferably with source);
     [java]     or, if your project is open source, information on where I can get the code from
     [java]         (I'm happy to checkout and build your project in order to investigate the error).
     [java] Apologies, and thank you for using Mutability Detector.
     [java]       At org.mutabilitydetector.checkers.UnhandledExceptionBuilder.unhandledException(UnhandledExceptionBuilder.java:54)
     [java]       At org.mutabilitydetector.checkers.CheckerRunner.attemptRecovery(CheckerRunner.java:79)
     [java]       At org.mutabilitydetector.checkers.CheckerRunner.run(CheckerRunner.java:66)
     [java]       At org.mutabilitydetector.checkers.AllChecksRunner.runCheckers(AllChecksRunner.java:65)
     [java]       At org.mutabilitydetector.ThreadUnsafeAnalysisSession.requestAnalysis(ThreadUnsafeAnalysisSession.java:118)
     [java]       At org.mutabilitydetector.ThreadUnsafeAnalysisSession.resultFor(ThreadUnsafeAnalysisSession.java:104)
     [java]       At org.mutabilitydetector.findbugs.IncorrectlyAppliedImmutableAnnotationDetector.doMutabilityAnalysis(IncorrectlyAppliedImmutableAnnotationDetector.java:72)
     [java]       At org.mutabilitydetector.findbugs.IncorrectlyAppliedImmutableAnnotationDetector.visitClassContext(IncorrectlyAppliedImmutableAnnotationDetector.java:66)
     [java]       At org.mutabilitydetector.findbugs.MutabilityDetector4FindBugs.visitClassContext(MutabilityDetector4FindBugs.java:47)
     [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
[INFO] Done FindBugs Analysis....

===============================================================
CODE: Class under analysis
===============================================================
package nick;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import jdk.nashorn.internal.ir.annotations.Immutable;

@SuppressWarnings("checkstyle:designforextension")
@SuppressFBWarnings
@Immutable
public class HistoryItem {
    private final int id;

    private int amount;
    private final String operation;
    private final int total;

    HistoryItem(final int id, final int amount, final String operation, final int total) {
        this.id = id;
        this.amount = amount;
        this.operation = operation;
        this.total = total;

    }

    public int getId() {
        return id;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(final int amount) {
        this.amount = amount;
    }

    public String getOperation() {
        return operation;
    }

    public int getTotal() {
        return total;
    }
    
}

==============================================
Upon further review, I found that the exception being thrown was a result of my
using the wrong annotation. I tried using "import javax.annotation.concurrent.Immutable" but that failed too with the same exception. I then tried "import net.jcip.annotations.Immutable" which allowed the detector to run without error - but it didn't catch the fact that the HistoryItem class is not immutable, it has a setAmount() method.

**Comment by Grundlefleck** [comment] 2018-06-22 21:19
Hey @nickantzoulis, thanks for taking the time to report.

Unfortunately it looks like the stack trace you have access to has just about everything except the interesting bit :( with all the wrapping of exceptions to try to be helpful, it looks to have lost the origin of the exception.

However, looking at the most recent version of the FindBugs plugin, I'm not surprised there are issues. I'm going to do a quick release that brings versions of things up to date, it could be something as irritating as a bytecode incompatibility that an update would fix. 

I'll update when a new release is available, and see if that happens to fix it. If not, I may need a bit more help to reproduce (version numbers, more stack trace if available, etc).

**Comment by Grundlefleck** [comment] 2018-06-22 22:03
Version 0.9.3 of the FindBugs plugin should be winging it's way to Maven Central. If you get a chance could you give that a try and get back to me?

**Comment by nickantzoulis** [comment] 2018-06-25 22:54
Will do. Which version of the '@Immutable' annotation should I be using?

**Comment by Grundlefleck** [comment] 2018-06-26 07:54
It should work with any annotation called "Immutable", the package doesn't
matter. See the logic for that here:
https://github.com/MutabilityDetector/MutabilityDetector4FindBugs/blob/fc29a7a39e054f1d58c8079fa6e06beae06f53be/src/main/java/org/mutabilitydetector/findbugs/IncorrectlyAppliedImmutableAnnotationDetector.java#L57

Although, it seems a bit sensitive to the casing. Does the annotation
you're using actually start with a lowercase 'i'? I don't think the plugin
needs to be specific about that so maybe that could be an enhancement to
work on. Though I don't expect that would account for the runtime exception.

**Comment by nickantzoulis** [comment] 2018-06-27 21:49
No, not using lowercase 'i'. The comment editor changed the case on me on submit:) Haven't had a chance to check the fix yet, but its on my list.

**Comment by Grundlefleck** [comment] 2019-01-09 22:11
@nickantzoulis if 0.9.3 didn't fix your issue, let me know and I'll reopen. I'm going to be really optimistic and assume it solved all your problems, and close the issue :)

**Closed by Grundlefleck** 2019-01-09 22:11 UTC
